# Generated by Django 3.1 on 2020-08-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text_content', models.CharField(max_length=255)),
                ('path_media_content', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255, null=True)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('telegram_id', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('substate', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeAnswerQuiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('path_media_content', models.CharField(max_length=255)),
                ('right_answer', models.CharField(max_length=255)),
                ('right_answer_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_primary_manual_roats', to='data.message')),
                ('wrong_answer_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrong_answer_action', to='data.message')),
            ],
        ),
    ]
