# Generated by Django 3.1 on 2020-08-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_user_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255, null=True)),
                ('next_substate', models.CharField(max_length=255, null=True)),
                ('previous_substate', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='next_button_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='previous_button_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='substate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
