# Generated by Django 3.1 on 2020-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200826_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedmessages',
            name='next_substate',
        ),
        migrations.RemoveField(
            model_name='linkedmessages',
            name='previous_substate',
        ),
        migrations.RemoveField(
            model_name='message',
            name='substate',
        ),
        migrations.AddField(
            model_name='linkedmessages',
            name='next_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='substate',
            field=models.IntegerField(null=True),
        ),
    ]
