# Generated by Django 3.1 on 2020-08-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200826_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeanswerquiz',
            name='hint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hint', to='data.message'),
        ),
        migrations.AddField(
            model_name='freeanswerquiz',
            name='next_quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_quiz', to='data.freeanswerquiz'),
        ),
        migrations.AlterField(
            model_name='message',
            name='path_media_content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
