# Generated by Django 3.1 on 2020-08-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200826_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeanswerquiz',
            name='path_media_content',
        ),
        migrations.AlterField(
            model_name='freeanswerquiz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='data.message'),
        ),
    ]
