# Generated by Django 3.1 on 2020-08-26 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200826_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeanswerquiz',
            name='next_quiz_id',
        ),
        migrations.AddField(
            model_name='freeanswerquiz',
            name='next_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_quiza', to='data.freeanswerquiz'),
        ),
    ]
