# Generated by Django 3.1 on 2020-08-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200826_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeanswerquiz',
            name='next_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_quiz_fk', to='data.freeanswerquiz'),
        ),
    ]
