# Generated by Django 3.1 on 2020-08-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_user_solving_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_task',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
