# Generated by Django 3.1 on 2020-08-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20200827_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solved_task_list',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
