# Generated by Django 3.1 on 2020-08-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_user_solved_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='solved_task_list',
            field=models.CharField(default='', max_length=512),
        ),
    ]
