# Generated by Django 3.1 on 2020-09-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20200830_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text_content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
