# Generated by Django 3.1 on 2020-09-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20200914_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicCommand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('command', models.CharField(max_length=255)),
                ('unixtime', models.IntegerField(null=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.message')),
            ],
        ),
    ]
